/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsumersRouteRouteImport } from './routes/consumers/route'
import { Route as AgentsRouteRouteImport } from './routes/agents/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as ConsumersIndexRouteImport } from './routes/consumers/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ConsumersServicesRouteImport } from './routes/consumers/services'
import { Route as ConsumersProfileRouteImport } from './routes/consumers/profile'
import { Route as ConsumersHistoryRouteImport } from './routes/consumers/history'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as AgentsRegisterRouteImport } from './routes/agents/register'
import { Route as ConsumersWorkerIdRouteImport } from './routes/consumers/worker.$id'
import { Route as ConsumersPaymentIdRouteImport } from './routes/consumers/payment.$id'
import { Route as ConsumersOrderIdRouteImport } from './routes/consumers/order.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ConsumersRouteRoute = ConsumersRouteRouteImport.update({
  id: '/consumers',
  path: '/consumers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRouteRoute = AgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersIndexRoute = ConsumersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRouteRoute,
} as any)
const ConsumersServicesRoute = ConsumersServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const ConsumersProfileRoute = ConsumersProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const ConsumersHistoryRoute = ConsumersHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AgentsRouteRoute,
} as any)
const ConsumersWorkerIdRoute = ConsumersWorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const ConsumersPaymentIdRoute = ConsumersPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const ConsumersOrderIdRoute = ConsumersOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => ConsumersRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRouteWithChildren
  '/consumers': typeof ConsumersRouteRouteWithChildren
  '/agents/register': typeof AgentsRegisterRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/consumers/history': typeof ConsumersHistoryRoute
  '/consumers/profile': typeof ConsumersProfileRoute
  '/consumers/services': typeof ConsumersServicesRoute
  '/agents/': typeof AgentsIndexRoute
  '/consumers/': typeof ConsumersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/consumers/order/$id': typeof ConsumersOrderIdRoute
  '/consumers/payment/$id': typeof ConsumersPaymentIdRoute
  '/consumers/worker/$id': typeof ConsumersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/consumers/history': typeof ConsumersHistoryRoute
  '/consumers/profile': typeof ConsumersProfileRoute
  '/consumers/services': typeof ConsumersServicesRoute
  '/agents': typeof AgentsIndexRoute
  '/consumers': typeof ConsumersIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/consumers/order/$id': typeof ConsumersOrderIdRoute
  '/consumers/payment/$id': typeof ConsumersPaymentIdRoute
  '/consumers/worker/$id': typeof ConsumersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRouteWithChildren
  '/consumers': typeof ConsumersRouteRouteWithChildren
  '/agents/register': typeof AgentsRegisterRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/consumers/history': typeof ConsumersHistoryRoute
  '/consumers/profile': typeof ConsumersProfileRoute
  '/consumers/services': typeof ConsumersServicesRoute
  '/agents/': typeof AgentsIndexRoute
  '/consumers/': typeof ConsumersIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/consumers/order/$id': typeof ConsumersOrderIdRoute
  '/consumers/payment/$id': typeof ConsumersPaymentIdRoute
  '/consumers/worker/$id': typeof ConsumersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/consumers'
    | '/agents/register'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/otp'
    | '/consumers/history'
    | '/consumers/profile'
    | '/consumers/services'
    | '/agents/'
    | '/consumers/'
    | '/workers/'
    | '/api/auth/$'
    | '/consumers/order/$id'
    | '/consumers/payment/$id'
    | '/consumers/worker/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/register'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/otp'
    | '/consumers/history'
    | '/consumers/profile'
    | '/consumers/services'
    | '/agents'
    | '/consumers'
    | '/workers'
    | '/api/auth/$'
    | '/consumers/order/$id'
    | '/consumers/payment/$id'
    | '/consumers/worker/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/consumers'
    | '/agents/register'
    | '/auth/complete'
    | '/auth/login'
    | '/auth/otp'
    | '/consumers/history'
    | '/consumers/profile'
    | '/consumers/services'
    | '/agents/'
    | '/consumers/'
    | '/workers/'
    | '/api/auth/$'
    | '/consumers/order/$id'
    | '/consumers/payment/$id'
    | '/consumers/worker/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRouteRoute: typeof AgentsRouteRouteWithChildren
  ConsumersRouteRoute: typeof ConsumersRouteRouteWithChildren
  AuthCompleteRoute: typeof AuthCompleteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consumers': {
      id: '/consumers'
      path: '/consumers'
      fullPath: '/consumers'
      preLoaderRoute: typeof ConsumersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers/': {
      id: '/consumers/'
      path: '/'
      fullPath: '/consumers/'
      preLoaderRoute: typeof ConsumersIndexRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRouteRoute
    }
    '/consumers/services': {
      id: '/consumers/services'
      path: '/services'
      fullPath: '/consumers/services'
      preLoaderRoute: typeof ConsumersServicesRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/consumers/profile': {
      id: '/consumers/profile'
      path: '/profile'
      fullPath: '/consumers/profile'
      preLoaderRoute: typeof ConsumersProfileRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/consumers/history': {
      id: '/consumers/history'
      path: '/history'
      fullPath: '/consumers/history'
      preLoaderRoute: typeof ConsumersHistoryRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof AgentsRouteRoute
    }
    '/consumers/worker/$id': {
      id: '/consumers/worker/$id'
      path: '/worker/$id'
      fullPath: '/consumers/worker/$id'
      preLoaderRoute: typeof ConsumersWorkerIdRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/consumers/payment/$id': {
      id: '/consumers/payment/$id'
      path: '/payment/$id'
      fullPath: '/consumers/payment/$id'
      preLoaderRoute: typeof ConsumersPaymentIdRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/consumers/order/$id': {
      id: '/consumers/order/$id'
      path: '/order/$id'
      fullPath: '/consumers/order/$id'
      preLoaderRoute: typeof ConsumersOrderIdRouteImport
      parentRoute: typeof ConsumersRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteRouteChildren {
  AgentsRegisterRoute: typeof AgentsRegisterRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteRouteChildren: AgentsRouteRouteChildren = {
  AgentsRegisterRoute: AgentsRegisterRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteRouteWithChildren = AgentsRouteRoute._addFileChildren(
  AgentsRouteRouteChildren,
)

interface ConsumersRouteRouteChildren {
  ConsumersHistoryRoute: typeof ConsumersHistoryRoute
  ConsumersProfileRoute: typeof ConsumersProfileRoute
  ConsumersServicesRoute: typeof ConsumersServicesRoute
  ConsumersIndexRoute: typeof ConsumersIndexRoute
  ConsumersOrderIdRoute: typeof ConsumersOrderIdRoute
  ConsumersPaymentIdRoute: typeof ConsumersPaymentIdRoute
  ConsumersWorkerIdRoute: typeof ConsumersWorkerIdRoute
}

const ConsumersRouteRouteChildren: ConsumersRouteRouteChildren = {
  ConsumersHistoryRoute: ConsumersHistoryRoute,
  ConsumersProfileRoute: ConsumersProfileRoute,
  ConsumersServicesRoute: ConsumersServicesRoute,
  ConsumersIndexRoute: ConsumersIndexRoute,
  ConsumersOrderIdRoute: ConsumersOrderIdRoute,
  ConsumersPaymentIdRoute: ConsumersPaymentIdRoute,
  ConsumersWorkerIdRoute: ConsumersWorkerIdRoute,
}

const ConsumersRouteRouteWithChildren = ConsumersRouteRoute._addFileChildren(
  ConsumersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRouteRoute: AgentsRouteRouteWithChildren,
  ConsumersRouteRoute: ConsumersRouteRouteWithChildren,
  AuthCompleteRoute: AuthCompleteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  WorkersIndexRoute: WorkersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
