/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentRouteImport } from './routes/_agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentDashboardRouteImport } from './routes/_agent.dashboard'
import { Route as AgentWorkersIndexRouteImport } from './routes/_agent.workers.index'
import { Route as AgentWorkersNewRouteImport } from './routes/_agent.workers.new'
import { Route as AgentWorkersWorkerIdRouteImport } from './routes/_agent.workers.$workerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/_agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkersIndexRoute = AgentWorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkersNewRoute = AgentWorkersNewRouteImport.update({
  id: '/workers/new',
  path: '/workers/new',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWorkersWorkerIdRoute = AgentWorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AgentDashboardRoute
  '/workers/$workerId': typeof AgentWorkersWorkerIdRoute
  '/workers/new': typeof AgentWorkersNewRoute
  '/workers/': typeof AgentWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AgentDashboardRoute
  '/workers/$workerId': typeof AgentWorkersWorkerIdRoute
  '/workers/new': typeof AgentWorkersNewRoute
  '/workers': typeof AgentWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/_agent/dashboard': typeof AgentDashboardRoute
  '/_agent/workers/$workerId': typeof AgentWorkersWorkerIdRoute
  '/_agent/workers/new': typeof AgentWorkersNewRoute
  '/_agent/workers/': typeof AgentWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/workers/$workerId'
    | '/workers/new'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/workers/$workerId'
    | '/workers/new'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_agent'
    | '/login'
    | '/_agent/dashboard'
    | '/_agent/workers/$workerId'
    | '/_agent/workers/new'
    | '/_agent/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agent': {
      id: '/_agent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agent/dashboard': {
      id: '/_agent/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof AgentRoute
    }
    '/_agent/workers/': {
      id: '/_agent/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AgentWorkersIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/_agent/workers/new': {
      id: '/_agent/workers/new'
      path: '/workers/new'
      fullPath: '/workers/new'
      preLoaderRoute: typeof AgentWorkersNewRouteImport
      parentRoute: typeof AgentRoute
    }
    '/_agent/workers/$workerId': {
      id: '/_agent/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof AgentWorkersWorkerIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AgentRouteChildren {
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentWorkersWorkerIdRoute: typeof AgentWorkersWorkerIdRoute
  AgentWorkersNewRoute: typeof AgentWorkersNewRoute
  AgentWorkersIndexRoute: typeof AgentWorkersIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentDashboardRoute: AgentDashboardRoute,
  AgentWorkersWorkerIdRoute: AgentWorkersWorkerIdRoute,
  AgentWorkersNewRoute: AgentWorkersNewRoute,
  AgentWorkersIndexRoute: AgentWorkersIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
